branch-defaults:
  master:
    environment: help-educate-dev
    group_suffix: null
environment-defaults:
  help-educate-dev:
    branch: null
    repository: null
global:
  application_name: help-educate
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
